categories:
  - title: 'New Features'
    label:
      - 'Feature'
      - 'Feature :boom:'
  - title: 'Improvements'
    labels:
      - 'enhancement'
      - 'Improvement'
      - 'Enhancement :tada:'
      - 'Improvement :tada:'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'Bug fix'
      - 'Bug :bug:'
      - 'Bug fix :bug:'
      - 'Bug Fix :bug:'
  - title: 'Breaking changes'
    label:
      - 'BC Break'
      - 'BC Break :fire"'
  - title: 'Environment Variable changes'
    label:
      - 'Env Change'
      - 'Env Change :man_technologist:'
  - title: 'External API Endpoint Changes'
    label:
      - 'Endpoint change'
      - 'Endpoint change :shipit:'
      - 'Endpoint Change :shipit:'
  - title: 'Dependencies'
    label: 
      - 'dependencies'
change-template: '- [#$NUMBER](https://github.com/thisisbud/release-drafter/pull/$NUMBER) $TITLE (@$AUTHOR)'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
template: |
  $CHANGES
